#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sip")]
	public partial class AbsensiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmesin_absen_log(mesin_absen_log instance);
    partial void Updatemesin_absen_log(mesin_absen_log instance);
    partial void Deletemesin_absen_log(mesin_absen_log instance);
    partial void Insertmesin_absensi(mesin_absensi instance);
    partial void Updatemesin_absensi(mesin_absensi instance);
    partial void Deletemesin_absensi(mesin_absensi instance);
    partial void Insertsekolah(sekolah instance);
    partial void Updatesekolah(sekolah instance);
    partial void Deletesekolah(sekolah instance);
    partial void Insertguru(guru instance);
    partial void Updateguru(guru instance);
    partial void Deleteguru(guru instance);
    partial void Insertabsen(absen instance);
    partial void Updateabsen(absen instance);
    partial void Deleteabsen(absen instance);
    partial void Insertsiswa(siswa instance);
    partial void Updatesiswa(siswa instance);
    partial void Deletesiswa(siswa instance);
    #endregion
		public AbsensiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mesin_absen_log> mesin_absen_logs
		{
			get
			{
				return this.GetTable<mesin_absen_log>();
			}
		}
		
		public System.Data.Linq.Table<mesin_absensi> mesin_absensis
		{
			get
			{
				return this.GetTable<mesin_absensi>();
			}
		}
		
		public System.Data.Linq.Table<sekolah> sekolahs
		{
			get
			{
				return this.GetTable<sekolah>();
			}
		}
		
		public System.Data.Linq.Table<guru> gurus
		{
			get
			{
				return this.GetTable<guru>();
			}
		}
		
		public System.Data.Linq.Table<absen> absens
		{
			get
			{
				return this.GetTable<absen>();
			}
		}
		
		public System.Data.Linq.Table<siswa> siswas
		{
			get
			{
				return this.GetTable<siswa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="mesin_absen_log")]
	public partial class mesin_absen_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _log_mesin_absen_id;
		
		private System.Nullable<int> _log_mesin_status;
		
		private System.Nullable<System.DateTime> _log_mesin_tgl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_mesin_absen_idChanging(string value);
    partial void Onlog_mesin_absen_idChanged();
    partial void Onlog_mesin_statusChanging(System.Nullable<int> value);
    partial void Onlog_mesin_statusChanged();
    partial void Onlog_mesin_tglChanging(System.Nullable<System.DateTime> value);
    partial void Onlog_mesin_tglChanged();
    #endregion
		
		public mesin_absen_log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_mesin_absen_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string log_mesin_absen_id
		{
			get
			{
				return this._log_mesin_absen_id;
			}
			set
			{
				if ((this._log_mesin_absen_id != value))
				{
					this.Onlog_mesin_absen_idChanging(value);
					this.SendPropertyChanging();
					this._log_mesin_absen_id = value;
					this.SendPropertyChanged("log_mesin_absen_id");
					this.Onlog_mesin_absen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_mesin_status", DbType="Int")]
		public System.Nullable<int> log_mesin_status
		{
			get
			{
				return this._log_mesin_status;
			}
			set
			{
				if ((this._log_mesin_status != value))
				{
					this.Onlog_mesin_statusChanging(value);
					this.SendPropertyChanging();
					this._log_mesin_status = value;
					this.SendPropertyChanged("log_mesin_status");
					this.Onlog_mesin_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_mesin_tgl", DbType="Date")]
		public System.Nullable<System.DateTime> log_mesin_tgl
		{
			get
			{
				return this._log_mesin_tgl;
			}
			set
			{
				if ((this._log_mesin_tgl != value))
				{
					this.Onlog_mesin_tglChanging(value);
					this.SendPropertyChanging();
					this._log_mesin_tgl = value;
					this.SendPropertyChanged("log_mesin_tgl");
					this.Onlog_mesin_tglChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="mesin_absensi")]
	public partial class mesin_absensi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mesinabsen_id;
		
		private string _mesinabsen_nomor;
		
		private string _mesinabsen_ip;
		
		private string _mesinabsen_token;
		
		private string _mesinabsen_keterangan;
		
		private string _mesinabsen_sekolah_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmesinabsen_idChanging(string value);
    partial void Onmesinabsen_idChanged();
    partial void Onmesinabsen_nomorChanging(string value);
    partial void Onmesinabsen_nomorChanged();
    partial void Onmesinabsen_ipChanging(string value);
    partial void Onmesinabsen_ipChanged();
    partial void Onmesinabsen_tokenChanging(string value);
    partial void Onmesinabsen_tokenChanged();
    partial void Onmesinabsen_keteranganChanging(string value);
    partial void Onmesinabsen_keteranganChanged();
    partial void Onmesinabsen_sekolah_idChanging(string value);
    partial void Onmesinabsen_sekolah_idChanged();
    #endregion
		
		public mesin_absensi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mesinabsen_id
		{
			get
			{
				return this._mesinabsen_id;
			}
			set
			{
				if ((this._mesinabsen_id != value))
				{
					this.Onmesinabsen_idChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_id = value;
					this.SendPropertyChanged("mesinabsen_id");
					this.Onmesinabsen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_nomor", DbType="VarChar(50)")]
		public string mesinabsen_nomor
		{
			get
			{
				return this._mesinabsen_nomor;
			}
			set
			{
				if ((this._mesinabsen_nomor != value))
				{
					this.Onmesinabsen_nomorChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_nomor = value;
					this.SendPropertyChanged("mesinabsen_nomor");
					this.Onmesinabsen_nomorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_ip", DbType="VarChar(50)")]
		public string mesinabsen_ip
		{
			get
			{
				return this._mesinabsen_ip;
			}
			set
			{
				if ((this._mesinabsen_ip != value))
				{
					this.Onmesinabsen_ipChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_ip = value;
					this.SendPropertyChanged("mesinabsen_ip");
					this.Onmesinabsen_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_token", DbType="VarChar(50)")]
		public string mesinabsen_token
		{
			get
			{
				return this._mesinabsen_token;
			}
			set
			{
				if ((this._mesinabsen_token != value))
				{
					this.Onmesinabsen_tokenChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_token = value;
					this.SendPropertyChanged("mesinabsen_token");
					this.Onmesinabsen_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_keterangan", DbType="VarChar(50)")]
		public string mesinabsen_keterangan
		{
			get
			{
				return this._mesinabsen_keterangan;
			}
			set
			{
				if ((this._mesinabsen_keterangan != value))
				{
					this.Onmesinabsen_keteranganChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_keterangan = value;
					this.SendPropertyChanged("mesinabsen_keterangan");
					this.Onmesinabsen_keteranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesinabsen_sekolah_id", DbType="VarChar(50)")]
		public string mesinabsen_sekolah_id
		{
			get
			{
				return this._mesinabsen_sekolah_id;
			}
			set
			{
				if ((this._mesinabsen_sekolah_id != value))
				{
					this.Onmesinabsen_sekolah_idChanging(value);
					this.SendPropertyChanging();
					this._mesinabsen_sekolah_id = value;
					this.SendPropertyChanged("mesinabsen_sekolah_id");
					this.Onmesinabsen_sekolah_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sekolah")]
	public partial class sekolah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sekolah_id;
		
		private string _nama_sekolah;
		
		private string _alamat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsekolah_idChanging(string value);
    partial void Onsekolah_idChanged();
    partial void Onnama_sekolahChanging(string value);
    partial void Onnama_sekolahChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public sekolah()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekolah_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sekolah_id
		{
			get
			{
				return this._sekolah_id;
			}
			set
			{
				if ((this._sekolah_id != value))
				{
					this.Onsekolah_idChanging(value);
					this.SendPropertyChanging();
					this._sekolah_id = value;
					this.SendPropertyChanged("sekolah_id");
					this.Onsekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_sekolah", DbType="VarChar(150)")]
		public string nama_sekolah
		{
			get
			{
				return this._nama_sekolah;
			}
			set
			{
				if ((this._nama_sekolah != value))
				{
					this.Onnama_sekolahChanging(value);
					this.SendPropertyChanging();
					this._nama_sekolah = value;
					this.SendPropertyChanged("nama_sekolah");
					this.Onnama_sekolahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(150)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="guru")]
	public partial class guru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _guru_id;
		
		private string _guru_sekolah_id;
		
		private string _guru_nama;
		
		private string _guru_nip;
		
		private string _guru_email;
		
		private string _guru_nomor_kartu;
		
		private string _guru_phone;
		
		private string _guru_jk;
		
		private string _guru_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onguru_idChanging(int value);
    partial void Onguru_idChanged();
    partial void Onguru_sekolah_idChanging(string value);
    partial void Onguru_sekolah_idChanged();
    partial void Onguru_namaChanging(string value);
    partial void Onguru_namaChanged();
    partial void Onguru_nipChanging(string value);
    partial void Onguru_nipChanged();
    partial void Onguru_emailChanging(string value);
    partial void Onguru_emailChanged();
    partial void Onguru_nomor_kartuChanging(string value);
    partial void Onguru_nomor_kartuChanged();
    partial void Onguru_phoneChanging(string value);
    partial void Onguru_phoneChanged();
    partial void Onguru_jkChanging(string value);
    partial void Onguru_jkChanged();
    partial void Onguru_statusChanging(string value);
    partial void Onguru_statusChanged();
    #endregion
		
		public guru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int guru_id
		{
			get
			{
				return this._guru_id;
			}
			set
			{
				if ((this._guru_id != value))
				{
					this.Onguru_idChanging(value);
					this.SendPropertyChanging();
					this._guru_id = value;
					this.SendPropertyChanged("guru_id");
					this.Onguru_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_sekolah_id", DbType="VarChar(50)")]
		public string guru_sekolah_id
		{
			get
			{
				return this._guru_sekolah_id;
			}
			set
			{
				if ((this._guru_sekolah_id != value))
				{
					this.Onguru_sekolah_idChanging(value);
					this.SendPropertyChanging();
					this._guru_sekolah_id = value;
					this.SendPropertyChanged("guru_sekolah_id");
					this.Onguru_sekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_nama", DbType="VarChar(50)")]
		public string guru_nama
		{
			get
			{
				return this._guru_nama;
			}
			set
			{
				if ((this._guru_nama != value))
				{
					this.Onguru_namaChanging(value);
					this.SendPropertyChanging();
					this._guru_nama = value;
					this.SendPropertyChanged("guru_nama");
					this.Onguru_namaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_nip", DbType="VarChar(50)")]
		public string guru_nip
		{
			get
			{
				return this._guru_nip;
			}
			set
			{
				if ((this._guru_nip != value))
				{
					this.Onguru_nipChanging(value);
					this.SendPropertyChanging();
					this._guru_nip = value;
					this.SendPropertyChanged("guru_nip");
					this.Onguru_nipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_email", DbType="VarChar(50)")]
		public string guru_email
		{
			get
			{
				return this._guru_email;
			}
			set
			{
				if ((this._guru_email != value))
				{
					this.Onguru_emailChanging(value);
					this.SendPropertyChanging();
					this._guru_email = value;
					this.SendPropertyChanged("guru_email");
					this.Onguru_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_nomor_kartu", DbType="VarChar(50)")]
		public string guru_nomor_kartu
		{
			get
			{
				return this._guru_nomor_kartu;
			}
			set
			{
				if ((this._guru_nomor_kartu != value))
				{
					this.Onguru_nomor_kartuChanging(value);
					this.SendPropertyChanging();
					this._guru_nomor_kartu = value;
					this.SendPropertyChanged("guru_nomor_kartu");
					this.Onguru_nomor_kartuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_phone", DbType="VarChar(50)")]
		public string guru_phone
		{
			get
			{
				return this._guru_phone;
			}
			set
			{
				if ((this._guru_phone != value))
				{
					this.Onguru_phoneChanging(value);
					this.SendPropertyChanging();
					this._guru_phone = value;
					this.SendPropertyChanged("guru_phone");
					this.Onguru_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_jk", DbType="VarChar(50)")]
		public string guru_jk
		{
			get
			{
				return this._guru_jk;
			}
			set
			{
				if ((this._guru_jk != value))
				{
					this.Onguru_jkChanging(value);
					this.SendPropertyChanging();
					this._guru_jk = value;
					this.SendPropertyChanged("guru_jk");
					this.Onguru_jkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guru_status", DbType="VarChar(50)")]
		public string guru_status
		{
			get
			{
				return this._guru_status;
			}
			set
			{
				if ((this._guru_status != value))
				{
					this.Onguru_statusChanging(value);
					this.SendPropertyChanging();
					this._guru_status = value;
					this.SendPropertyChanged("guru_status");
					this.Onguru_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="absen")]
	public partial class absen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _absen_id;
		
		private string _absen_sekolah_id;
		
		private string _absen_nomor_kartu;
		
		private string _absen_kal_akademik_id;
		
		private string _absen_status;
		
		private string _absen_group;
		
		private System.Nullable<System.DateTime> _absen_tanggal;
		
		private System.Nullable<System.TimeSpan> _absen_masuk;
		
		private System.Nullable<System.TimeSpan> _absen_keluar;
		
		private string _absen_device;
		
		private System.Nullable<System.DateTime> _InsertAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onabsen_idChanging(string value);
    partial void Onabsen_idChanged();
    partial void Onabsen_sekolah_idChanging(string value);
    partial void Onabsen_sekolah_idChanged();
    partial void Onabsen_nomor_kartuChanging(string value);
    partial void Onabsen_nomor_kartuChanged();
    partial void Onabsen_kal_akademik_idChanging(string value);
    partial void Onabsen_kal_akademik_idChanged();
    partial void Onabsen_statusChanging(string value);
    partial void Onabsen_statusChanged();
    partial void Onabsen_groupChanging(string value);
    partial void Onabsen_groupChanged();
    partial void Onabsen_tanggalChanging(System.Nullable<System.DateTime> value);
    partial void Onabsen_tanggalChanged();
    partial void Onabsen_masukChanging(System.Nullable<System.TimeSpan> value);
    partial void Onabsen_masukChanged();
    partial void Onabsen_keluarChanging(System.Nullable<System.TimeSpan> value);
    partial void Onabsen_keluarChanged();
    partial void Onabsen_deviceChanging(string value);
    partial void Onabsen_deviceChanged();
    partial void OnInsertAtChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertAtChanged();
    #endregion
		
		public absen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string absen_id
		{
			get
			{
				return this._absen_id;
			}
			set
			{
				if ((this._absen_id != value))
				{
					this.Onabsen_idChanging(value);
					this.SendPropertyChanging();
					this._absen_id = value;
					this.SendPropertyChanged("absen_id");
					this.Onabsen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_sekolah_id", DbType="VarChar(50)")]
		public string absen_sekolah_id
		{
			get
			{
				return this._absen_sekolah_id;
			}
			set
			{
				if ((this._absen_sekolah_id != value))
				{
					this.Onabsen_sekolah_idChanging(value);
					this.SendPropertyChanging();
					this._absen_sekolah_id = value;
					this.SendPropertyChanged("absen_sekolah_id");
					this.Onabsen_sekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_nomor_kartu", DbType="VarChar(50)")]
		public string absen_nomor_kartu
		{
			get
			{
				return this._absen_nomor_kartu;
			}
			set
			{
				if ((this._absen_nomor_kartu != value))
				{
					this.Onabsen_nomor_kartuChanging(value);
					this.SendPropertyChanging();
					this._absen_nomor_kartu = value;
					this.SendPropertyChanged("absen_nomor_kartu");
					this.Onabsen_nomor_kartuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_kal_akademik_id", DbType="VarChar(50)")]
		public string absen_kal_akademik_id
		{
			get
			{
				return this._absen_kal_akademik_id;
			}
			set
			{
				if ((this._absen_kal_akademik_id != value))
				{
					this.Onabsen_kal_akademik_idChanging(value);
					this.SendPropertyChanging();
					this._absen_kal_akademik_id = value;
					this.SendPropertyChanged("absen_kal_akademik_id");
					this.Onabsen_kal_akademik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_status", DbType="VarChar(50)")]
		public string absen_status
		{
			get
			{
				return this._absen_status;
			}
			set
			{
				if ((this._absen_status != value))
				{
					this.Onabsen_statusChanging(value);
					this.SendPropertyChanging();
					this._absen_status = value;
					this.SendPropertyChanged("absen_status");
					this.Onabsen_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_group", DbType="VarChar(50)")]
		public string absen_group
		{
			get
			{
				return this._absen_group;
			}
			set
			{
				if ((this._absen_group != value))
				{
					this.Onabsen_groupChanging(value);
					this.SendPropertyChanging();
					this._absen_group = value;
					this.SendPropertyChanged("absen_group");
					this.Onabsen_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> absen_tanggal
		{
			get
			{
				return this._absen_tanggal;
			}
			set
			{
				if ((this._absen_tanggal != value))
				{
					this.Onabsen_tanggalChanging(value);
					this.SendPropertyChanging();
					this._absen_tanggal = value;
					this.SendPropertyChanged("absen_tanggal");
					this.Onabsen_tanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_masuk", DbType="Time")]
		public System.Nullable<System.TimeSpan> absen_masuk
		{
			get
			{
				return this._absen_masuk;
			}
			set
			{
				if ((this._absen_masuk != value))
				{
					this.Onabsen_masukChanging(value);
					this.SendPropertyChanging();
					this._absen_masuk = value;
					this.SendPropertyChanged("absen_masuk");
					this.Onabsen_masukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_keluar", DbType="Time")]
		public System.Nullable<System.TimeSpan> absen_keluar
		{
			get
			{
				return this._absen_keluar;
			}
			set
			{
				if ((this._absen_keluar != value))
				{
					this.Onabsen_keluarChanging(value);
					this.SendPropertyChanging();
					this._absen_keluar = value;
					this.SendPropertyChanged("absen_keluar");
					this.Onabsen_keluarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_device", DbType="VarChar(50)")]
		public string absen_device
		{
			get
			{
				return this._absen_device;
			}
			set
			{
				if ((this._absen_device != value))
				{
					this.Onabsen_deviceChanging(value);
					this.SendPropertyChanging();
					this._absen_device = value;
					this.SendPropertyChanged("absen_device");
					this.Onabsen_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> InsertAt
		{
			get
			{
				return this._InsertAt;
			}
			set
			{
				if ((this._InsertAt != value))
				{
					this.OnInsertAtChanging(value);
					this.SendPropertyChanging();
					this._InsertAt = value;
					this.SendPropertyChanged("InsertAt");
					this.OnInsertAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="siswa")]
	public partial class siswa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siswa_id;
		
		private string _siswa_sekolah_id;
		
		private string _siswa_nama;
		
		private string _siswa_kelas_id;
		
		private string _siswa_status;
		
		private string _siswa_nisn;
		
		private string _siswa_jk;
		
		private string _siswa_tempat_lahir;
		
		private string _siswa_tanggal_lahir;
		
		private string _siswa_alamat;
		
		private string _siswa_hp;
		
		private string _nama_panggilan;
		
		private string _siswa_waktu;
		
		private string _siswa_jarak;
		
		private string _siswa_email;
		
		private string _siswa_anak_ke;
		
		private string _siswa_jumlah_sudara;
		
		private string _siswa_kode_pos;
		
		private string _siswa_no_telp;
		
		private string _siswa_no_ijazah;
		
		private string _siswa_nik;
		
		private string _siswa_no_kk;
		
		private string _siswa_nomor_kartu;
		
		private string _siswa_tanggal_langganan;
		
		private string _siswa_kelurahan;
		
		private string _siswa_kecamatan;
		
		private string _siswa_kabupaten;
		
		private string _siswa_provinsi;
		
		private string _siswa_agama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsiswa_idChanging(string value);
    partial void Onsiswa_idChanged();
    partial void Onsiswa_sekolah_idChanging(string value);
    partial void Onsiswa_sekolah_idChanged();
    partial void Onsiswa_namaChanging(string value);
    partial void Onsiswa_namaChanged();
    partial void Onsiswa_kelas_idChanging(string value);
    partial void Onsiswa_kelas_idChanged();
    partial void Onsiswa_statusChanging(string value);
    partial void Onsiswa_statusChanged();
    partial void Onsiswa_nisnChanging(string value);
    partial void Onsiswa_nisnChanged();
    partial void Onsiswa_jkChanging(string value);
    partial void Onsiswa_jkChanged();
    partial void Onsiswa_tempat_lahirChanging(string value);
    partial void Onsiswa_tempat_lahirChanged();
    partial void Onsiswa_tanggal_lahirChanging(string value);
    partial void Onsiswa_tanggal_lahirChanged();
    partial void Onsiswa_alamatChanging(string value);
    partial void Onsiswa_alamatChanged();
    partial void Onsiswa_hpChanging(string value);
    partial void Onsiswa_hpChanged();
    partial void Onnama_panggilanChanging(string value);
    partial void Onnama_panggilanChanged();
    partial void Onsiswa_waktuChanging(string value);
    partial void Onsiswa_waktuChanged();
    partial void Onsiswa_jarakChanging(string value);
    partial void Onsiswa_jarakChanged();
    partial void Onsiswa_emailChanging(string value);
    partial void Onsiswa_emailChanged();
    partial void Onsiswa_anak_keChanging(string value);
    partial void Onsiswa_anak_keChanged();
    partial void Onsiswa_jumlah_sudaraChanging(string value);
    partial void Onsiswa_jumlah_sudaraChanged();
    partial void Onsiswa_kode_posChanging(string value);
    partial void Onsiswa_kode_posChanged();
    partial void Onsiswa_no_telpChanging(string value);
    partial void Onsiswa_no_telpChanged();
    partial void Onsiswa_no_ijazahChanging(string value);
    partial void Onsiswa_no_ijazahChanged();
    partial void Onsiswa_nikChanging(string value);
    partial void Onsiswa_nikChanged();
    partial void Onsiswa_no_kkChanging(string value);
    partial void Onsiswa_no_kkChanged();
    partial void Onsiswa_nomor_kartuChanging(string value);
    partial void Onsiswa_nomor_kartuChanged();
    partial void Onsiswa_tanggal_langgananChanging(string value);
    partial void Onsiswa_tanggal_langgananChanged();
    partial void Onsiswa_kelurahanChanging(string value);
    partial void Onsiswa_kelurahanChanged();
    partial void Onsiswa_kecamatanChanging(string value);
    partial void Onsiswa_kecamatanChanged();
    partial void Onsiswa_kabupatenChanging(string value);
    partial void Onsiswa_kabupatenChanged();
    partial void Onsiswa_provinsiChanging(string value);
    partial void Onsiswa_provinsiChanged();
    partial void Onsiswa_agamaChanging(string value);
    partial void Onsiswa_agamaChanged();
    #endregion
		
		public siswa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string siswa_id
		{
			get
			{
				return this._siswa_id;
			}
			set
			{
				if ((this._siswa_id != value))
				{
					this.Onsiswa_idChanging(value);
					this.SendPropertyChanging();
					this._siswa_id = value;
					this.SendPropertyChanged("siswa_id");
					this.Onsiswa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_sekolah_id", DbType="VarChar(50)")]
		public string siswa_sekolah_id
		{
			get
			{
				return this._siswa_sekolah_id;
			}
			set
			{
				if ((this._siswa_sekolah_id != value))
				{
					this.Onsiswa_sekolah_idChanging(value);
					this.SendPropertyChanging();
					this._siswa_sekolah_id = value;
					this.SendPropertyChanged("siswa_sekolah_id");
					this.Onsiswa_sekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_nama", DbType="VarChar(50)")]
		public string siswa_nama
		{
			get
			{
				return this._siswa_nama;
			}
			set
			{
				if ((this._siswa_nama != value))
				{
					this.Onsiswa_namaChanging(value);
					this.SendPropertyChanging();
					this._siswa_nama = value;
					this.SendPropertyChanged("siswa_nama");
					this.Onsiswa_namaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_kelas_id", DbType="VarChar(50)")]
		public string siswa_kelas_id
		{
			get
			{
				return this._siswa_kelas_id;
			}
			set
			{
				if ((this._siswa_kelas_id != value))
				{
					this.Onsiswa_kelas_idChanging(value);
					this.SendPropertyChanging();
					this._siswa_kelas_id = value;
					this.SendPropertyChanged("siswa_kelas_id");
					this.Onsiswa_kelas_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_status", DbType="VarChar(50)")]
		public string siswa_status
		{
			get
			{
				return this._siswa_status;
			}
			set
			{
				if ((this._siswa_status != value))
				{
					this.Onsiswa_statusChanging(value);
					this.SendPropertyChanging();
					this._siswa_status = value;
					this.SendPropertyChanged("siswa_status");
					this.Onsiswa_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_nisn", DbType="VarChar(50)")]
		public string siswa_nisn
		{
			get
			{
				return this._siswa_nisn;
			}
			set
			{
				if ((this._siswa_nisn != value))
				{
					this.Onsiswa_nisnChanging(value);
					this.SendPropertyChanging();
					this._siswa_nisn = value;
					this.SendPropertyChanged("siswa_nisn");
					this.Onsiswa_nisnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_jk", DbType="VarChar(50)")]
		public string siswa_jk
		{
			get
			{
				return this._siswa_jk;
			}
			set
			{
				if ((this._siswa_jk != value))
				{
					this.Onsiswa_jkChanging(value);
					this.SendPropertyChanging();
					this._siswa_jk = value;
					this.SendPropertyChanged("siswa_jk");
					this.Onsiswa_jkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_tempat_lahir", DbType="VarChar(50)")]
		public string siswa_tempat_lahir
		{
			get
			{
				return this._siswa_tempat_lahir;
			}
			set
			{
				if ((this._siswa_tempat_lahir != value))
				{
					this.Onsiswa_tempat_lahirChanging(value);
					this.SendPropertyChanging();
					this._siswa_tempat_lahir = value;
					this.SendPropertyChanged("siswa_tempat_lahir");
					this.Onsiswa_tempat_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_tanggal_lahir", DbType="VarChar(50)")]
		public string siswa_tanggal_lahir
		{
			get
			{
				return this._siswa_tanggal_lahir;
			}
			set
			{
				if ((this._siswa_tanggal_lahir != value))
				{
					this.Onsiswa_tanggal_lahirChanging(value);
					this.SendPropertyChanging();
					this._siswa_tanggal_lahir = value;
					this.SendPropertyChanged("siswa_tanggal_lahir");
					this.Onsiswa_tanggal_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_alamat", DbType="VarChar(50)")]
		public string siswa_alamat
		{
			get
			{
				return this._siswa_alamat;
			}
			set
			{
				if ((this._siswa_alamat != value))
				{
					this.Onsiswa_alamatChanging(value);
					this.SendPropertyChanging();
					this._siswa_alamat = value;
					this.SendPropertyChanged("siswa_alamat");
					this.Onsiswa_alamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_hp", DbType="VarChar(50)")]
		public string siswa_hp
		{
			get
			{
				return this._siswa_hp;
			}
			set
			{
				if ((this._siswa_hp != value))
				{
					this.Onsiswa_hpChanging(value);
					this.SendPropertyChanging();
					this._siswa_hp = value;
					this.SendPropertyChanged("siswa_hp");
					this.Onsiswa_hpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_panggilan", DbType="VarChar(50)")]
		public string nama_panggilan
		{
			get
			{
				return this._nama_panggilan;
			}
			set
			{
				if ((this._nama_panggilan != value))
				{
					this.Onnama_panggilanChanging(value);
					this.SendPropertyChanging();
					this._nama_panggilan = value;
					this.SendPropertyChanged("nama_panggilan");
					this.Onnama_panggilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_waktu", DbType="VarChar(50)")]
		public string siswa_waktu
		{
			get
			{
				return this._siswa_waktu;
			}
			set
			{
				if ((this._siswa_waktu != value))
				{
					this.Onsiswa_waktuChanging(value);
					this.SendPropertyChanging();
					this._siswa_waktu = value;
					this.SendPropertyChanged("siswa_waktu");
					this.Onsiswa_waktuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_jarak", DbType="VarChar(50)")]
		public string siswa_jarak
		{
			get
			{
				return this._siswa_jarak;
			}
			set
			{
				if ((this._siswa_jarak != value))
				{
					this.Onsiswa_jarakChanging(value);
					this.SendPropertyChanging();
					this._siswa_jarak = value;
					this.SendPropertyChanged("siswa_jarak");
					this.Onsiswa_jarakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_email", DbType="VarChar(50)")]
		public string siswa_email
		{
			get
			{
				return this._siswa_email;
			}
			set
			{
				if ((this._siswa_email != value))
				{
					this.Onsiswa_emailChanging(value);
					this.SendPropertyChanging();
					this._siswa_email = value;
					this.SendPropertyChanged("siswa_email");
					this.Onsiswa_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_anak_ke", DbType="VarChar(50)")]
		public string siswa_anak_ke
		{
			get
			{
				return this._siswa_anak_ke;
			}
			set
			{
				if ((this._siswa_anak_ke != value))
				{
					this.Onsiswa_anak_keChanging(value);
					this.SendPropertyChanging();
					this._siswa_anak_ke = value;
					this.SendPropertyChanged("siswa_anak_ke");
					this.Onsiswa_anak_keChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_jumlah_sudara", DbType="VarChar(50)")]
		public string siswa_jumlah_sudara
		{
			get
			{
				return this._siswa_jumlah_sudara;
			}
			set
			{
				if ((this._siswa_jumlah_sudara != value))
				{
					this.Onsiswa_jumlah_sudaraChanging(value);
					this.SendPropertyChanging();
					this._siswa_jumlah_sudara = value;
					this.SendPropertyChanged("siswa_jumlah_sudara");
					this.Onsiswa_jumlah_sudaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_kode_pos", DbType="VarChar(50)")]
		public string siswa_kode_pos
		{
			get
			{
				return this._siswa_kode_pos;
			}
			set
			{
				if ((this._siswa_kode_pos != value))
				{
					this.Onsiswa_kode_posChanging(value);
					this.SendPropertyChanging();
					this._siswa_kode_pos = value;
					this.SendPropertyChanged("siswa_kode_pos");
					this.Onsiswa_kode_posChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_no_telp", DbType="VarChar(50)")]
		public string siswa_no_telp
		{
			get
			{
				return this._siswa_no_telp;
			}
			set
			{
				if ((this._siswa_no_telp != value))
				{
					this.Onsiswa_no_telpChanging(value);
					this.SendPropertyChanging();
					this._siswa_no_telp = value;
					this.SendPropertyChanged("siswa_no_telp");
					this.Onsiswa_no_telpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_no_ijazah", DbType="VarChar(50)")]
		public string siswa_no_ijazah
		{
			get
			{
				return this._siswa_no_ijazah;
			}
			set
			{
				if ((this._siswa_no_ijazah != value))
				{
					this.Onsiswa_no_ijazahChanging(value);
					this.SendPropertyChanging();
					this._siswa_no_ijazah = value;
					this.SendPropertyChanged("siswa_no_ijazah");
					this.Onsiswa_no_ijazahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_nik", DbType="VarChar(50)")]
		public string siswa_nik
		{
			get
			{
				return this._siswa_nik;
			}
			set
			{
				if ((this._siswa_nik != value))
				{
					this.Onsiswa_nikChanging(value);
					this.SendPropertyChanging();
					this._siswa_nik = value;
					this.SendPropertyChanged("siswa_nik");
					this.Onsiswa_nikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_no_kk", DbType="VarChar(50)")]
		public string siswa_no_kk
		{
			get
			{
				return this._siswa_no_kk;
			}
			set
			{
				if ((this._siswa_no_kk != value))
				{
					this.Onsiswa_no_kkChanging(value);
					this.SendPropertyChanging();
					this._siswa_no_kk = value;
					this.SendPropertyChanged("siswa_no_kk");
					this.Onsiswa_no_kkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_nomor_kartu", DbType="VarChar(50)")]
		public string siswa_nomor_kartu
		{
			get
			{
				return this._siswa_nomor_kartu;
			}
			set
			{
				if ((this._siswa_nomor_kartu != value))
				{
					this.Onsiswa_nomor_kartuChanging(value);
					this.SendPropertyChanging();
					this._siswa_nomor_kartu = value;
					this.SendPropertyChanged("siswa_nomor_kartu");
					this.Onsiswa_nomor_kartuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_tanggal_langganan", DbType="VarChar(50)")]
		public string siswa_tanggal_langganan
		{
			get
			{
				return this._siswa_tanggal_langganan;
			}
			set
			{
				if ((this._siswa_tanggal_langganan != value))
				{
					this.Onsiswa_tanggal_langgananChanging(value);
					this.SendPropertyChanging();
					this._siswa_tanggal_langganan = value;
					this.SendPropertyChanged("siswa_tanggal_langganan");
					this.Onsiswa_tanggal_langgananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_kelurahan", DbType="VarChar(50)")]
		public string siswa_kelurahan
		{
			get
			{
				return this._siswa_kelurahan;
			}
			set
			{
				if ((this._siswa_kelurahan != value))
				{
					this.Onsiswa_kelurahanChanging(value);
					this.SendPropertyChanging();
					this._siswa_kelurahan = value;
					this.SendPropertyChanged("siswa_kelurahan");
					this.Onsiswa_kelurahanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_kecamatan", DbType="VarChar(50)")]
		public string siswa_kecamatan
		{
			get
			{
				return this._siswa_kecamatan;
			}
			set
			{
				if ((this._siswa_kecamatan != value))
				{
					this.Onsiswa_kecamatanChanging(value);
					this.SendPropertyChanging();
					this._siswa_kecamatan = value;
					this.SendPropertyChanged("siswa_kecamatan");
					this.Onsiswa_kecamatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_kabupaten", DbType="VarChar(50)")]
		public string siswa_kabupaten
		{
			get
			{
				return this._siswa_kabupaten;
			}
			set
			{
				if ((this._siswa_kabupaten != value))
				{
					this.Onsiswa_kabupatenChanging(value);
					this.SendPropertyChanging();
					this._siswa_kabupaten = value;
					this.SendPropertyChanged("siswa_kabupaten");
					this.Onsiswa_kabupatenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_provinsi", DbType="VarChar(50)")]
		public string siswa_provinsi
		{
			get
			{
				return this._siswa_provinsi;
			}
			set
			{
				if ((this._siswa_provinsi != value))
				{
					this.Onsiswa_provinsiChanging(value);
					this.SendPropertyChanging();
					this._siswa_provinsi = value;
					this.SendPropertyChanged("siswa_provinsi");
					this.Onsiswa_provinsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siswa_agama", DbType="VarChar(50)")]
		public string siswa_agama
		{
			get
			{
				return this._siswa_agama;
			}
			set
			{
				if ((this._siswa_agama != value))
				{
					this.Onsiswa_agamaChanging(value);
					this.SendPropertyChanging();
					this._siswa_agama = value;
					this.SendPropertyChanged("siswa_agama");
					this.Onsiswa_agamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
