#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostComSip
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sip")]
	public partial class AbsensiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsekolah(sekolah instance);
    partial void Updatesekolah(sekolah instance);
    partial void Deletesekolah(sekolah instance);
    partial void Insertabsen(absen instance);
    partial void Updateabsen(absen instance);
    partial void Deleteabsen(absen instance);
    #endregion
		public AbsensiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbsensiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sekolah> sekolahs
		{
			get
			{
				return this.GetTable<sekolah>();
			}
		}
		
		public System.Data.Linq.Table<absen> absens
		{
			get
			{
				return this.GetTable<absen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sekolah")]
	public partial class sekolah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sekolah_id;
		
		private string _nama_sekolah;
		
		private string _alamat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsekolah_idChanging(string value);
    partial void Onsekolah_idChanged();
    partial void Onnama_sekolahChanging(string value);
    partial void Onnama_sekolahChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public sekolah()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekolah_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sekolah_id
		{
			get
			{
				return this._sekolah_id;
			}
			set
			{
				if ((this._sekolah_id != value))
				{
					this.Onsekolah_idChanging(value);
					this.SendPropertyChanging();
					this._sekolah_id = value;
					this.SendPropertyChanged("sekolah_id");
					this.Onsekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_sekolah", DbType="VarChar(150)")]
		public string nama_sekolah
		{
			get
			{
				return this._nama_sekolah;
			}
			set
			{
				if ((this._nama_sekolah != value))
				{
					this.Onnama_sekolahChanging(value);
					this.SendPropertyChanging();
					this._nama_sekolah = value;
					this.SendPropertyChanged("nama_sekolah");
					this.Onnama_sekolahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(150)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.absen")]
	public partial class absen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _absen_id;
		
		private string _absen_sekolah_id;
		
		private string _absen_nomor_kartu;
		
		private string _absen_kal_akademik_id;
		
		private string _absen_status;
		
		private string _absen_group;
		
		private System.Nullable<System.DateTime> _absen_tanggal;
		
		private System.Nullable<System.TimeSpan> _absen_masuk;
		
		private System.Nullable<System.TimeSpan> _absen_keluar;
		
		private string _absen_device;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onabsen_idChanging(string value);
    partial void Onabsen_idChanged();
    partial void Onabsen_sekolah_idChanging(string value);
    partial void Onabsen_sekolah_idChanged();
    partial void Onabsen_nomor_kartuChanging(string value);
    partial void Onabsen_nomor_kartuChanged();
    partial void Onabsen_kal_akademik_idChanging(string value);
    partial void Onabsen_kal_akademik_idChanged();
    partial void Onabsen_statusChanging(string value);
    partial void Onabsen_statusChanged();
    partial void Onabsen_groupChanging(string value);
    partial void Onabsen_groupChanged();
    partial void Onabsen_tanggalChanging(System.Nullable<System.DateTime> value);
    partial void Onabsen_tanggalChanged();
    partial void Onabsen_masukChanging(System.Nullable<System.TimeSpan> value);
    partial void Onabsen_masukChanged();
    partial void Onabsen_keluarChanging(System.Nullable<System.TimeSpan> value);
    partial void Onabsen_keluarChanged();
    partial void Onabsen_deviceChanging(string value);
    partial void Onabsen_deviceChanged();
    #endregion
		
		public absen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string absen_id
		{
			get
			{
				return this._absen_id;
			}
			set
			{
				if ((this._absen_id != value))
				{
					this.Onabsen_idChanging(value);
					this.SendPropertyChanging();
					this._absen_id = value;
					this.SendPropertyChanged("absen_id");
					this.Onabsen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_sekolah_id", DbType="VarChar(50)")]
		public string absen_sekolah_id
		{
			get
			{
				return this._absen_sekolah_id;
			}
			set
			{
				if ((this._absen_sekolah_id != value))
				{
					this.Onabsen_sekolah_idChanging(value);
					this.SendPropertyChanging();
					this._absen_sekolah_id = value;
					this.SendPropertyChanged("absen_sekolah_id");
					this.Onabsen_sekolah_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_nomor_kartu", DbType="VarChar(50)")]
		public string absen_nomor_kartu
		{
			get
			{
				return this._absen_nomor_kartu;
			}
			set
			{
				if ((this._absen_nomor_kartu != value))
				{
					this.Onabsen_nomor_kartuChanging(value);
					this.SendPropertyChanging();
					this._absen_nomor_kartu = value;
					this.SendPropertyChanged("absen_nomor_kartu");
					this.Onabsen_nomor_kartuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_kal_akademik_id", DbType="VarChar(50)")]
		public string absen_kal_akademik_id
		{
			get
			{
				return this._absen_kal_akademik_id;
			}
			set
			{
				if ((this._absen_kal_akademik_id != value))
				{
					this.Onabsen_kal_akademik_idChanging(value);
					this.SendPropertyChanging();
					this._absen_kal_akademik_id = value;
					this.SendPropertyChanged("absen_kal_akademik_id");
					this.Onabsen_kal_akademik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_status", DbType="VarChar(50)")]
		public string absen_status
		{
			get
			{
				return this._absen_status;
			}
			set
			{
				if ((this._absen_status != value))
				{
					this.Onabsen_statusChanging(value);
					this.SendPropertyChanging();
					this._absen_status = value;
					this.SendPropertyChanged("absen_status");
					this.Onabsen_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_group", DbType="VarChar(50)")]
		public string absen_group
		{
			get
			{
				return this._absen_group;
			}
			set
			{
				if ((this._absen_group != value))
				{
					this.Onabsen_groupChanging(value);
					this.SendPropertyChanging();
					this._absen_group = value;
					this.SendPropertyChanged("absen_group");
					this.Onabsen_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> absen_tanggal
		{
			get
			{
				return this._absen_tanggal;
			}
			set
			{
				if ((this._absen_tanggal != value))
				{
					this.Onabsen_tanggalChanging(value);
					this.SendPropertyChanging();
					this._absen_tanggal = value;
					this.SendPropertyChanged("absen_tanggal");
					this.Onabsen_tanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_masuk", DbType="Time")]
		public System.Nullable<System.TimeSpan> absen_masuk
		{
			get
			{
				return this._absen_masuk;
			}
			set
			{
				if ((this._absen_masuk != value))
				{
					this.Onabsen_masukChanging(value);
					this.SendPropertyChanging();
					this._absen_masuk = value;
					this.SendPropertyChanged("absen_masuk");
					this.Onabsen_masukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_keluar", DbType="Time")]
		public System.Nullable<System.TimeSpan> absen_keluar
		{
			get
			{
				return this._absen_keluar;
			}
			set
			{
				if ((this._absen_keluar != value))
				{
					this.Onabsen_keluarChanging(value);
					this.SendPropertyChanging();
					this._absen_keluar = value;
					this.SendPropertyChanged("absen_keluar");
					this.Onabsen_keluarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_absen_device", DbType="VarChar(50)")]
		public string absen_device
		{
			get
			{
				return this._absen_device;
			}
			set
			{
				if ((this._absen_device != value))
				{
					this.Onabsen_deviceChanging(value);
					this.SendPropertyChanging();
					this._absen_device = value;
					this.SendPropertyChanged("absen_device");
					this.Onabsen_deviceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
